# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'seniorios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for seniorios
	pod 'Alamofire'
pod 'AlamofireObjectMapper'
  target 'senioriosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'senioriosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
